spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/bibliotek
    username: root
    password: chemnitz2023
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

